image: continuumio/miniconda3:latest

stages:
  - install
  - test
  - docs
  - test_dev
  - test_dev_optional

before_script:
  - apt-get update -q -y
  - apt install -y libgl1-mesa-glx build-essential
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install mamba
  - mamba env create -f conda/skijumpdesign-lib.yml
  - mamba env create -f conda/skijumpdesign-lib-dev.yml
  - mamba env create -f conda/skijumpdesign-lib-opt-dev.yml
  - mamba info

install:
  script:
    - source activate skijumpdesign-lib
    - python setup.py install
    - which skijumpdesign

test:
  script:
    - source activate skijumpdesign-lib
    - mamba list
    - python -c "import skijumpdesign"

test_dev:
  script:
    - source activate skijumpdesign-lib-dev
    - mamba list
    - py.test --cov=skijumpdesign

test_dev_optional:
  script:
    - source activate skijumpdesign-lib-opt-dev
    - mamba list
    - py.test --cov=skijumpdesign

docs:
  script:
    - source activate skijumpdesign-lib-dev
    - cd docs/
    - make html
