image: continuumio/miniconda3:latest

stages:
  - install
  - test
  - docs

before_script:
  - conda config --set always_yes yes
  - conda update -q conda
  - conda env create -f environment.yml
  - source activate skijumpdesign
  - conda info
  - conda list

install:
  script:
    - python setup.py install

test:
  script:
    - py.test --cov=skijumpdesign

docs:
  script:
    - cd docs/
    - make html
