name: safeskijump
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - pip
  - ipython
  - spyder
  - numpy
  - scipy >=1.0  # requires solve_ivp()
  - matplotlib
  - sympy
  - cython
  - pytest
  - nbformat  # plotly dep, oddly not included in conda dep
  - jupyter_core  # plotly dep, oddly not included in conda dep
  - plotly
  - flask
  - flask-compress
  - pip:
    - dash
    - dash-renderer
    - dash-html-components
    - dash-core-components
