name: skijumpdesign-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - ipython
  - numpy >=0.13.0  # requires new options in gradient()
  - pandas
  - scipy >=1.0  # requires solve_ivp()
  - matplotlib
  - sympy
  - cython
  - fastcache
  - pytest
  - coverage
  - pytest-cov
  - pyinstrument
  - sphinx
  - flask
  - plotly
  - dash
  - dash-renderer
  - dash-html-components
  - dash-core-components
  - dash-table
