name: skijumpdesign-dev-optional
channels:
  - conda-forge
dependencies:
  - coverage
  - cython
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer
  - dash-table
  - fastcache
  - flask
  - ipython
  - matplotlib
  - numpy >=0.13.0  # requires new options in gradient()
  - pandas
  - plotly
  - pycvodes
  - pyinstrument
  - pytest
  - pytest-cov
  - python >=3.6
  - scipy >=1.0  # requires solve_ivp()
  - setuptools
  - sphinx
  - sympy
  - xlrd
