name: skijumpdesign-dev-optional
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7.1
  - setuptools = 40.8.0
  - ipython = 7.3.0
  - numpy = 1.16.2  # requires new options in gradient()
  - pandas = 0.24.1
  - scipy = 1.21  # requires solve_ivp()
  - matplotlib = 3.0.3
  - sympy = 1.3
  - cython = 0.29.6
  - fastcache = 1.0.2
  - pycvodes
  - pytest = 4.3.0
  - coverage = 4.5.2
  - pytest-cov = 2.6.1
  - pyinstrument = 3.0.1
  - sphinx = 1.8.4
  - flask = 1.0.2
  - plotly = 3.6.1
  - dash = 0.36.1
  - dash-renderer = 0.19.0
  - dash-html-components = 0.13.5
  - dash-core-components = 0.43.1
  - dash-table = 3.4.0
