name: skijumpdesign
channels:
  - conda-forge
  - defaults
dependencies:
  - python ==3.6*
  - setuptools
  - numpy ==1.15.0
  - scipy ==1.1.0
  - matplotlib ==2.2.3
  - sympy ==1.2
  - cython ==0.28.5
  - fastcache ==1.0.2
  - flask ==1.0.2
  - plotly ==3.1.1
  - dash ==0.25.0
  - dash-renderer ==0.13.2
  - dash-html-components ==0.11.0
  - dash-core-components ==0.27.1
