name: skijumpdesign
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - setuptools
  - numpy >=0.13.0  # requires new options in gradient()
  - scipy >=1.0  # requires solve_ivp()
  - matplotlib
  - sympy
  - cython
  - fastcache
  - flask
  - plotly
  - dash
  - dash-renderer
  - dash-html-components
  - dash-core-components
